### ISSUE TITLE
Brainstorm official name of extension

### ISSUE THREAD

**Issue by kerrykimrusso** [kerrykimrusso/target-blank#10]
Wanted to call it ~Anchor~ but there's a handful of extensions already called that.

We could try an alternate spelling like ~Anker, Ankr, or Anchr~. Not sure if I'm thrilled about that though. 

Other names:
- ~Lynx~, ~Linkz~, ~Links~, ~Linked~
- Hreferee (GG.)
- ~LInkaroo~
- ~New Tab~
- ~_Blank~

Or we go with Target-Blank.

Think of any?

**Comment by BeejLuig** [comment]
[Anker](https://www.anker.com/) is already taken, so I'd probably say let's just stay far away from that one haha.

I link __blank_ or __Blank_. H-referee is hilarious but maybe too much? If we go with _Lynx_ we at least have our mascot sorted out.

I'll see if I can come up with a couple original ideas too.

**Comment by BeejLuig** [comment]
Idea from last week: Tabby/Tabbi/Tabbey

**Comment by BeejLuig** [comment]
bullseye - "grab links by the horn"
anchor ref - "make links follow your rules"
