### ISSUE TITLE
Extension not running for new links on Github when URL updates but page does not refresh

### ISSUE THREAD

**Issue by kerrykimrusso** [kerrykimrusso/target-blank#11]
I'm fairly certain the issue here is that the page is being updated through JS and the window.history is getting the updated URL pushed to it, so it's not triggering the _contentscript_ to run again. This seems to only happen when clicking on a file, not a folder. I think we'll have to listen to changes in window.history in order run our _contentscript_ again. **We shouldn't process any links twice though.**

**Comment by BeejLuig** [comment]
I'm thinking we probably want to tackle this with a [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). We should be able to track the altered (or new) nodes and handle them accordingly
