### ISSUE TITLE
Sleep Mode / Toggle Extension

### ISSUE THREAD

**Issue by BeejLuig** [kerrykimrusso/target-blank#13]
In the popup options, it would be nice to have a quick dropdown of sleep timers, with increasing durations. Something like: 

- 5min
- 15min
- 30min
- 1hr
- 2hr

Also, it would be helpful to have a sort of power button to toggle the entire extension's functionality

**Comment by kerrykimrusso** [comment]
accc19a16a8a7ca1719c43d6dd86442ecf3f7166 completes the functionality/logic of this. We'll still need to figure out the UI.
