### ISSUE TITLE
Whitelist Option

### ISSUE THREAD

**Issue by BeejLuig** [kerrykimrusso/target-blank#16]
Add an option to whitelist urls. 

- Full path or origin?
- Add a "whitelist this page" button to the popup options
- Add a "remove from whitelist" button to the popup options (if already whitelisted)
- Add a "manage whitelist" link

Rendering the buttons should be a matter of determining the path (or origin) of the window from the content script then passing that information over to options.js

**Comment by kerrykimrusso** [comment]
My initial version of this has been pushed to branch whitelist. With respect to the bullets above:
[x] Full path or origin? *I am using the origin, including the subdomain and not the entire URL*
[x] Add a "whitelist this page" button to the popup options 
[x] Add a "remove from whitelist" button to the popup options (if already whitelisted)
[ ] Add a "manage whitelist" link

**Comment by kerrykimrusso** [comment]
Creating separate issue for "Add a "manage whitelist" link"
