### ISSUE TITLE
Facebook messages bug

### ISSUE THREAD

**Issue by kerrykimrusso** [kerrykimrusso/target-blank#17]
**Current behavior:** After clicking on a fb message in the dropdown list of messages, the message opens, but the list of messages remains open. 

**Expected behavior:** List of messages closes after opening a message.

Haven't looked into the cause yet.

**Comment by BeejLuig** [comment]
@kerrykimrusso I'm assuming this is on facebook.com, not messenger.com. Are we sure this isn't the default behavior? I just tried this out on an incognito tab with the same effect.

**Comment by kerrykimrusso** [comment]
@BeejLuig I had our refactor branch checked out so that's one thing that probably contributed. I checked out the master branch and tried it again and it seems to be working. Closing!
