### ISSUE TITLE
Google search result links

### ISSUE THREAD

**Issue by kerrykimrusso** [kerrykimrusso/target-blank#19]
Are your Google search result links being formatted like:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=12&cad=rja&uact=8&ved=0ahUKEwiCnKHHl_vWAhUFySYKHVlPAwoQFgiPATAL&url=http%3A%2F%2Fwww.nbcsports.com%2Fphiladelphia%2Fflyers&usg=AOvVaw1I9rW2y-rz3zMuAgNxH0Gu

I feel like I randomly see this with Google. It makes all of the links then behave like relative links rather than absolute.

**Comment by BeejLuig** [comment]
I thought we handled this issue and put it in a strategy a while ago. I guess it got deleted somewhere down the line :/

**Comment by kerrykimrusso** [comment]
welp, guess github didn't like my commit message that said it fixes this issue...

for posterity: closed by c3bc0bf650cc3a786fe2e854d72e6a3c072dbf9e
