### ISSUE TITLE
Not preventing default behavior 

### ISSUE THREAD

**Issue by kerrykimrusso** [kerrykimrusso/target-blank#3]
On broadstreethockey.com, when I clicked on a story, it was opening and focusing the new tab, however it was still loading the page in the original tab as well. 

I also clicked on an download link on justinmind.com and it had the same behavior, though didn't seem to try and download the file twice.

**Comment by BeejLuig** [comment]
I'm seeing the same issue with news links on yahoo.com.

**Comment by kerrykimrusso** [comment]
I think we need to setup different strategies for specific domains and also a general/default/fallback strategy. So our Strategy class/object public api just be:

- matchesDomain(window.location.origin):bool
- shouldIgnore(anchor):bool -> tests to see if this is something we should ignore, for example on a Google app, we'd ignore the account and app link clicks

Then in our contentscript we can just loop over all of our strategies and only test the ones that the domain matches:

const strategies = [googleStrat, yahooStrat, defaultStrat]

for(let i = 0; i < strategies.length; ++i) {
  if(strategies[i].matchesDomain(window.location.origin)) {
    if(strategies[i].shouldIgnore(a)) return;
  }
}

I think we're going to be running into more of these specific cases and this should help keep things organized. Let me know if this makes sense.

**Comment by BeejLuig** [comment]
Just found another one. A new tab is opening when selecting a chat within the Facebook desktop app. hrefs are something like `https://www.facebook.com/messages/t/<message-id>`

**Comment by kerrykimrusso** [comment]
These webapps are gonna be a real problem for us in general I feel. 

I'm not seeing that behavior for fb messages though. I think I should be seeing it. I'm on the yahoo-strategy branch and have the latest pushed code. It doesn't look like the click event listener is being added to the messages link for me. It's being added the 'New Message' link though and I'm console.log('clicked', href)-ing but it's just opening the typical message box in the bottom-right. No errors in the background.js either but no tab is being opened.

**Comment by BeejLuig** [comment]
I'll see if I can replicate the issue and share a gif or something. Or I can just show you next time we work on it
