### ISSUE TITLE
Heroku "Getting Started" Tutorial Buttons 404'ing

### ISSUE THREAD

**Issue by BeejLuig** [kerrykimrusso/target-blank#33]
https://devcenter.heroku.com/articles/getting-started-with-ruby#introduction

At the bottom of every chapter in this tutorial is a link to proceed to the next chapter. For example, the first link looks like this: `<a class="btn btn-lg btn-primary js-button js-complete" href="introduction">I'm ready to start</a>`'

The only problem is that the href is actually an indication of where you are, not where you are going. The app is using JS to handle the navigation with event listeners.

Another proposal: let's have a list to handle edge cases like this where we default the subpath as whitelisted. Only one link is breaking per-page here, but it would be enough to make someone want to pull their hair out. We could add a warning to the options saying "remove from whitelist at your own risk". We could also have an indicator icon to say "hey we know something doesn't work on this page"

**Comment by kerrykimrusso** [comment]
WON'T FIX. Latest iteration of extension is opt-in.
